#ifndef _LABNATION_SMARTSCOPE_REGS_H
#define _LABNATION_SMARTSCOPE_REGS_H

#include <map>
#include <vector>
#include "memory/register.h"

namespace labnation {

const int HDR_OFFSET = 15;
const int SZ_HDR = 64;
const int PACKAGE_MAX = 64;
const int SZ_OVERVIEW = 2048 * 2;
const int ACQUISITION_DEPTH_MIN = 128; //Size of RAM
const int ACQUISITION_DEPTH_MAX = 4 * 1024 * 1024; //Size of RAM
const int FETCH_SIZE_MAX = 2048 * 2;

#define LIST_PIC \
  X(FORCE_STREAMING, 0)

#define LIST_REG \
  X(STROBE_UPDATE, 0) \
  X(SPI_ADDRESS, 1) \
  X(SPI_WRITE_VALUE, 2) \
  X(DIVIDER_MULTIPLIER, 3) \
  X(CHA_YOFFSET_VOLTAGE, 4) \
  X(CHB_YOFFSET_VOLTAGE, 5) \
  X(TRIGGER_PWM, 6) \
  X(TRIGGER_LEVEL, 7) \
  X(TRIGGER_MODE, 8) \
  X(TRIGGER_PW_MIN_B0, 9) \
  X(TRIGGER_PW_MIN_B1, 10) \
  X(TRIGGER_PW_MIN_B2, 11) \
  X(TRIGGER_PW_MAX_B0, 12) \
  X(TRIGGER_PW_MAX_B1, 13) \
  X(TRIGGER_PW_MAX_B2, 14) \
  X(INPUT_DECIMATION, 15) \
  X(ACQUISITION_DEPTH, 16) \
  X(TRIGGERHOLDOFF_B0, 17) \
  X(TRIGGERHOLDOFF_B1, 18) \
  X(TRIGGERHOLDOFF_B2, 19) \
  X(TRIGGERHOLDOFF_B3, 20) \
  X(VIEW_DECIMATION, 21) \
  X(VIEW_OFFSET_B0, 22) \
  X(VIEW_OFFSET_B1, 23) \
  X(VIEW_OFFSET_B2, 24) \
  X(VIEW_ACQUISITIONS, 25) \
  X(VIEW_BURSTS, 26) \
  X(VIEW_EXCESS_B0, 27) \
  X(VIEW_EXCESS_B1, 28) \
  X(DIGITAL_TRIGGER_RISING, 29) \
  X(DIGITAL_TRIGGER_FALLING, 30) \
  X(DIGITAL_TRIGGER_HIGH, 31) \
  X(DIGITAL_TRIGGER_LOW, 32) \
  X(DIGITAL_OUT, 33) \
  X(GENERATOR_DECIMATION_B0, 34) \
  X(GENERATOR_DECIMATION_B1, 35) \
  X(GENERATOR_DECIMATION_B2, 36) \
  X(GENERATOR_SAMPLES_B0, 37) \
  X(GENERATOR_SAMPLES_B1, 38)

#define LIST_STR \
  X(GLOBAL_RESET, 0) \
  X(INIT_SPI_TRANSFER, 1) \
  X(GENERATOR_TO_AWG, 2) \
  X(LA_ENABLE, 3) \
  X(SCOPE_ENABLE, 4) \
  X(SCOPE_UPDATE, 5) \
  X(FORCE_TRIGGER, 6) \
  X(VIEW_UPDATE, 7) \
  X(VIEW_SEND_OVERVIEW, 8) \
  X(VIEW_SEND_PARTIAL, 9) \
  X(ACQ_START, 10) \
  X(ACQ_STOP, 11) \
  X(CHA_DCCOUPLING, 12) \
  X(CHB_DCCOUPLING, 13) \
  X(ENABLE_ADC, 14) \
  X(ENABLE_NEG, 15) \
  X(ENABLE_RAM, 16) \
  X(DOUT_3V_5V, 17) \
  X(EN_OPAMP_B, 18) \
  X(GENERATOR_TO_DIGITAL, 19) \
  X(ROLL, 20) \
  X(LA_CHANNEL, 21)

#define LIST_ROM \
  X(FW_GIT0, 0) \
  X(FW_GIT1, 1) \
  X(FW_GIT2, 2) \
  X(FW_GIT3, 3) \
  X(SPI_RECEIVED_VALUE, 4) \
  X(STROBES, 5)

#define X(name, value) name = value,
enum REG { LIST_REG };
enum STR { LIST_STR };
enum ROM { LIST_ROM };
#undef X

static std::map<REG, int> HDR_REGS
{
  { TRIGGER_LEVEL, 0 },
  { TRIGGER_MODE, 1 },
  { TRIGGERHOLDOFF_B0, 2 },
  { TRIGGERHOLDOFF_B1, 3 },
  { TRIGGERHOLDOFF_B2, 4 },
  { TRIGGERHOLDOFF_B3, 5 },
  { CHA_YOFFSET_VOLTAGE, 6 },
  { CHB_YOFFSET_VOLTAGE, 7 },
  { DIVIDER_MULTIPLIER, 8 },
  { INPUT_DECIMATION, 9 },
  { TRIGGER_PW_MIN_B0, 10 },
  { TRIGGER_PW_MIN_B1, 11 },
  { TRIGGER_PW_MIN_B2, 12 },
  { TRIGGER_PW_MAX_B0, 13 },
  { TRIGGER_PW_MAX_B1, 14 },
  { TRIGGER_PW_MAX_B2, 15 },
  { TRIGGER_PWM, 16 },
  { DIGITAL_TRIGGER_RISING, 17 },
  { DIGITAL_TRIGGER_FALLING, 18 },
  { DIGITAL_TRIGGER_HIGH, 19 },
  { DIGITAL_TRIGGER_LOW, 20 },
  { ACQUISITION_DEPTH, 21 },
  { VIEW_DECIMATION, 22 },
  { VIEW_OFFSET_B0, 23 },
  { VIEW_OFFSET_B1, 24 },
  { VIEW_OFFSET_B2, 25 },
  { VIEW_ACQUISITIONS, 26 },
  { VIEW_BURSTS, 27 },
  { VIEW_EXCESS_B0, 28 },
  { VIEW_EXCESS_B1, 29 },
};
const int N_HDR_REGS = 30;


static std::map<STR, int> HDR_STROBES =
{
  { LA_ENABLE, 0 },
  { CHA_DCCOUPLING, 1 },
  { CHB_DCCOUPLING, 2 },
  { ROLL, 3 },
  { LA_CHANNEL, 4 },
};
const int N_HDR_STROBES = 5;



static std::vector<STR> AcquisitionStrobes =
{
  LA_ENABLE,
  CHA_DCCOUPLING,
  CHB_DCCOUPLING,
  ROLL,
  LA_CHANNEL,
};


static std::vector<REG> AcquisitionRegisters =
{
  TRIGGER_LEVEL,
  TRIGGER_MODE,
  TRIGGERHOLDOFF_B0,
  TRIGGERHOLDOFF_B1,
  TRIGGERHOLDOFF_B2,
  TRIGGERHOLDOFF_B3,
  CHA_YOFFSET_VOLTAGE,
  CHB_YOFFSET_VOLTAGE,
  DIVIDER_MULTIPLIER,
  INPUT_DECIMATION,
  TRIGGER_PW_MIN_B0,
  TRIGGER_PW_MIN_B1,
  TRIGGER_PW_MIN_B2,
  TRIGGER_PW_MAX_B0,
  TRIGGER_PW_MAX_B1,
  TRIGGER_PW_MAX_B2,
  TRIGGER_PWM,
  DIGITAL_TRIGGER_RISING,
  DIGITAL_TRIGGER_FALLING,
  DIGITAL_TRIGGER_HIGH,
  DIGITAL_TRIGGER_LOW,
  ACQUISITION_DEPTH,
};


static std::vector<REG> ViewRegisters =
{
  VIEW_DECIMATION,
  VIEW_OFFSET_B0,
  VIEW_OFFSET_B1,
  VIEW_OFFSET_B2,
  VIEW_ACQUISITIONS,
  VIEW_BURSTS,
  VIEW_EXCESS_B0,
  VIEW_EXCESS_B1,
};

}

#endif // _LABNATION_SMARTSCOPE_REGS_H
